version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
       - .:/usr/app-mobile-chat/
       - /usr/app-mobile-chat/node_modules/

networks:
  default:
    name: simple-chat-admin