version: '3.8'
services:
  # NodeJS API container
  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      mysql:
        condition: service_started
    ports:
      - 3001:3001
    volumes:
       - .:/usr/app-mobile-chat/
       - /usr/app-mobile-chat/node_modules/
    environment:
      DB_HOST: mysql
      DB_NAME: chat_api
      DB_USER: root
      DB_PASSWORD: root
      DB_PORT: 8889
    networks:
      - backend
      - frontend

  # MySQL container
  mysql:
    container_name: mysql
    image: mariadb:latest
    expose:
      - '3306'
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: chat_api
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
  
  # phpMyAdmin image
  phpmyadmin:
    container_name: phpmyadmin
    image: 'phpmyadmin/phpmyadmin'
    links:
      - 'mysql:mysql'
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
    networks:
      - backend

volumes:
  db:

networks:
  backend:
  frontend: